### ISSUE TITLE
Error adding BlocProvider to app

### ISSUE THREAD

**Issue by Oga-Emma** [robertohuertasm/generic_bloc_provider#3]
Compiler message:
lib/widgets/screens/dashboard/corporate_action/cooperate_action.dart:44:16: Error: Inferred type argument 'Type' doesn't conform to the bound 'Bloc' of the type variable 'T' on 'BlocProvider'.
 - 'Type' is from 'dart:core'.
 - 'Bloc' is from 'package:generic_bloc_provider/src/bloc.dart' ('file:///Users/seven/development/flutter/.pub-cache/hosted/pub.dartlang.org/generic_bloc_provider-1.0.9/lib/src/bloc.dart').
Try specifying type arguments explicitly so that they conform to the bounds.
        child: BlocProvider(
               ^
file:///Users/seven/development/flutter/.pub-cache/hosted/pub.dartlang.org/generic_bloc_provider-1.0.9/lib/src/bloc_provider.dart:6:20: Context: This is the type variable whose bound isn't conformed to.
class BlocProvider<T extends Bloc> extends StatefulWidget {
                   ^

**Comment by robertohuertasm** [comment]
It seems that probably the `BLoC` that you're using doesn't extend the `Bloc` abstract class.

**Comment by Oga-Emma** [comment]
import 'package:africaprudential/services/corporate_actions.dart';
import 'package:generic_bloc_provider/generic_bloc_provider.dart';
import 'package:rxdart/rxdart.dart';

class CorporateActionBloc extends Bloc{

  CorporateActionBloc(){
    fetchCorporateData();
  }

  var corporateActionsController = BehaviorSubject<dynamic>();
  Sink<dynamic> get corporateActionsSink => corporateActionsController.sink;
  Observable<dynamic> corporateStream(){
    //fetch data and populate
    fetchCorporateData();
    return corporateActionsController.stream;
  }

  void fetchCorporateData(){
    CorporateActions.fetch()
        .then((dynamic data){
      print("CORPERATE ACTIONS ==> $data");

    }).catchError((){

    });
  }

  @override
  void dispose() {
    corporateActionsSink.close();
  }

}

**Comment by Oga-Emma** [comment]
I did, there is my code. help me look into it please.

**Comment by robertohuertasm** [comment]
which version of flutter are you using?

**Comment by Oga-Emma** [comment]
Flutter (Channel stable, v1.2.1)

**Comment by robertohuertasm** [comment]
If is it not much to ask, can you share the actual code having the error?

**Comment by Oga-Emma** [comment]
import 'dart:async';

import 'package:africaprudential/bloc/corporate_actions_bloc.dart';
import 'package:africaprudential/constants/mk_routes.dart';
import 'package:africaprudential/constants/mk_strings.dart';
import 'package:africaprudential/environments/environment.dart';
import 'package:africaprudential/main.dart';
import 'package:africaprudential/rebloc/actions/common.dart';
import 'package:africaprudential/rebloc/main.dart';
import 'package:africaprudential/rebloc/states/main.dart';
import 'package:africaprudential/utils/mk_navigate.dart';
import 'package:africaprudential/utils/mk_screen_util.dart';
import 'package:africaprudential/utils/mk_settings.dart';
import 'package:africaprudential/utils/mk_theme.dart';
import 'package:africaprudential/widgets/screens/dashboard/settings_new/settings_tab.dart';
import 'package:africaprudential/widgets/screens/launch/launch_screen_page.dart';
import 'package:africaprudential/widgets/screens/login/login_page.dart';
import 'package:africaprudential/widgets/screens/splash/splash_page.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:generic_bloc_provider/generic_bloc_provider.dart';
import 'package:rebloc/rebloc.dart';

class BootstrapModel {
  const BootstrapModel({
    @required this.isFirstTime,
  });

  final bool isFirstTime;
}

class App extends StatefulWidget {
  App({
    @required Environment env,
    @required this.isFirstTime,
  }) {
    MkSettings.environment = env;
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.dark);
    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  }

  final bool isFirstTime;

  static Future<BootstrapModel> bootstrap() async {
    final isFirstTime = await MkSettings.checkIsFirstTimeLogin();
    try {
      await MkSettings.initVersion();
    } catch (e) {
      //
    }

    return BootstrapModel(isFirstTime: isFirstTime);
  }

  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  final Store<AppState> store = reblocStore();

  final MkScreenUtilConfig screenConfig = const MkScreenUtilConfig(
    width: 375,
    height: 812,
    allowFontScaling: true,
  );

  @override
  void dispose() {
    store.dispatcher(const OnDisposeAction());
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MkTheme(
      child: BlocProvider(                           //HERE IS THE LINE
        bloc: CorporateActionBloc,
        child: StoreProvider<AppState>(
          store: store,
          child: FirstBuildDispatcher<AppState>(
            // Initialize action
            action: const OnInitAction(),
            child: Builder(
              builder: (BuildContext context) {
                return MaterialApp(
                  debugShowCheckedModeBanner: false,
                  title: MkStrings.appName,
                  color: Colors.white,
                  theme: MkTheme.of(context).themeData(Theme.of(context)),
                  builder: (context, child) {
                    return Builder(
                      builder: (BuildContext context) {
                        MkScreenUtil.initialize(
                          context: context,
                          config: screenConfig,
                        );
                        return child;
                      },
                    );
                  },
                  onGenerateRoute: (RouteSettings settings) {
                    return MkNavigateRoute<dynamic>(
                      builder: (_) => LaunchScreenPage(),
                      settings: settings.copyWith(
                        name: MkRoutes.start,
                        isInitialRoute: true,
                      ),
                    );
                  },
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by robertohuertasm** [comment]
Sorry, it's been a while and I hadn't the time to look more into this. Is this still an issue? If not I will close it next week.
