### ISSUE TITLE
Some functions dont work after braking changes on firebase 

### ISSUE THREAD

**Issue by JERV-code** [robertohuertasm/generic_bloc_provider#8]
Currently i am trying to implement Firebase Auth 0.18.3 functions but some of them dont makes the acctions on them ... the sign Out mainly

**Comment by robertohuertasm** [comment]
Sorry, I don't understand what you mean. Can you be more specific?

**Comment by JERV-code** [comment]
sorry, I couldnt explain myself, I'm using generic bloc provider to implement some firebase functions through a Bloc class and use them with some screens.

with some future functions dont run, before the changes on firebase auth 0.18.0 it use to work perfect

**Comment by robertohuertasm** [comment]
I would need an example project to reproduce this. Whiteout more details it's difficult to know anything.

**Comment by robertohuertasm** [comment]
Closing this as I don't have a way to reproduce it.
