### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by derbec** [robertohuertasm/generic_bloc_provider#9]
Any plans to migrate generic_bloc_provider to null safety?

https://dart.dev/null-safety/migration-guide

Cheers !

Derek

**Comment by robertohuertasm** [comment]
Hi @derbec!

To be honest, not for the moment... but now that you mention it I'll look into it.

Thanks for the suggestion!

**Comment by robertohuertasm** [comment]
Done! It's already published!

**Comment by robertohuertasm** [comment]
Check the [pre-release version in pub.dev](https://pub.dev/packages/generic_bloc_provider/versions/2.0.0-nullsafety.0)

**Comment by derbec** [comment]
Thanks Roberto, quick work!
